#### About

> Tensors

Tensors are mathematical objects that generalize scalars, vectors, and matrices to higher dimensions. In Python, tensors can be represented using PyTorch, NumPy arrays, which provide efficient array operations and numerical computations.

In [2]:
import torch

# Define a 3-dimensional tensor
T = torch.tensor([
  [[1, 2], [3, 4]],
  [[5, 6], [7, 8]],
  [[9, 10], [11, 12]]
])

In [3]:
# Print the tensor and its shape
print(T)
print(T.shape)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
torch.Size([3, 2, 2])


In [4]:
# Accessing elements of a tensor
print(T[1, 0, 1]) 

tensor(6)


In [5]:
# Changing elements of a tensor
T[2, 1, 1] = 0
print(T)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11,  0]]])


In [6]:
# Tensor operations
T1 = torch.tensor([
  [[1, 2], [3, 4]],
  [[5, 6], [7, 8]],
  [[9, 10], [11, 12]]
])

T2 = torch.tensor([
  [[2, 3], [4, 5]],
  [[6, 7], [8, 9]],
  [[10, 11], [12, 13]]
])


In [7]:

T3 = T1 + T2
print(T3)

T4 = torch.matmul(T1, T2)
print(T4)

tensor([[[ 3,  5],
         [ 7,  9]],

        [[11, 13],
         [15, 17]],

        [[19, 21],
         [23, 25]]])
tensor([[[ 10,  13],
         [ 22,  29]],

        [[ 78,  89],
         [106, 121]],

        [[210, 229],
         [254, 277]]])
