#### About
> Singular value decomposition

Singular Value Decomposition (SVD) is a matrix factorization method that decomposes a matrix into three matrices: U, Σ, and V, where U and V are orthogonal matrices and Σ is a diagonal matrix containing the singular values of the original matrix.

SVD is commonly used in machine learning for dimensionality reduction, noise reduction, and data compression. It can also be used for image compression, recommendation systems, and natural language processing.




In [1]:
import numpy as np

# create a 3x2 matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# perform SVD
U, S, V = np.linalg.svd(A)

# print the original matrix
print("Original matrix:")
print(A)

# print the left singular vectors (U matrix)
print("Left singular vectors (U matrix):")
print(U)

# print the singular values (Σ matrix)
print("Singular values (Σ matrix):")
print(np.diag(S))

# print the right singular vectors (V matrix)
print("Right singular vectors (V matrix):")
print(V)

Original matrix:
[[1 2]
 [3 4]
 [5 6]]
Left singular vectors (U matrix):
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular values (Σ matrix):
[[9.52551809 0.        ]
 [0.         0.51430058]]
Right singular vectors (V matrix):
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
