#### About

> QR-Factorization

QR factorization is a matrix factorization technique that decomposes a matrix into the product of an orthogonal matrix Q and an upper triangular matrix R. This decomposition can be useful in solving systems of linear equations, computing eigenvalues and eigenvectors, and other applications.



In [1]:
import numpy as np


In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [3]:
# Perform QR factorization
Q, R = np.linalg.qr(A)

In [4]:
# Print the results
print("Matrix A:\n", A)
print("Matrix Q:\n", Q)
print("Matrix R:\n", R)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix Q:
 [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
Matrix R:
 [[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]
