#### About

> Singular value thresholding.

Singular Value Thresholding (SVT) is a matrix completion technique that uses singular value decomposition (SVD) to recover low-rank matrices from incomplete or corrupted data. In the context of linear algebra, SVT involves computing the SVD of a matrix, setting the singular values below a certain threshold to zero, and reconstructing the matrix using the modified singular values.



In [1]:
import numpy as np


In [6]:

def svt(A, tau, max_iter=100, tol=1e-6):
    # Replace NaN values with zeros
    A = np.nan_to_num(A)
    # Scale the matrix to have values in the range [0, 1]
    A_scaled = (A - np.nanmin(A)) / (np.nanmax(A) - np.nanmin(A))
    # Apply SVT
    X = A_scaled.copy()
    for i in range(max_iter):
        U, s, V = np.linalg.svd(X, full_matrices=False)
        s_thresh = np.maximum(s - tau, 0)
        X_new = U.dot(np.diag(s_thresh)).dot(V)
        if np.linalg.norm(X_new - X) / np.linalg.norm(X) < tol:
            break
        X = X_new
    # Rescale the matrix to the original range
    A_complete = A.copy()
    A_complete[~np.isnan(A)] = X_new.flatten() * (np.nanmax(A) - np.nanmin(A)) + np.nanmin(A)
    return A_complete


In [7]:
A = np.array([[1, 2, np.nan], [3, np.nan, 4], [np.nan, 5, 6]])
A_complete = svt(A, tau=1.0)
print(A_complete)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


/tmp/ipykernel_25438/37062102.py:12: RuntimeWarning: invalid value encountered in double_scalars
  if np.linalg.norm(X_new - X) / np.linalg.norm(X) < tol:
