#### About

> Sparse matrix

A sparse matrix is a matrix in which most of the elements are zero. Sparse matrices arise frequently in various applications, such as graph theory, finite element analysis, and image processing, where the matrices can be very large and have many zero entries. To store sparse matrices, we typically use specialized data structures that take advantage of their sparsity to reduce storage requirements and improve computational efficiency.



In [1]:
import numpy as np
from scipy.sparse import csr_matrix

In [2]:
data = np.array([1, 2, 3, 4, 5, 6])
row_indices = np.array([0, 0, 1, 1, 2, 2])
col_indices = np.array([0, 2, 1, 2, 0, 1])
sparse_matrix = csr_matrix((data, (row_indices, col_indices)), shape=(3, 3))


In [3]:
# Print the sparse matrix
print(sparse_matrix)

  (0, 0)	1
  (0, 2)	2
  (1, 1)	3
  (1, 2)	4
  (2, 0)	5
  (2, 1)	6


In [4]:
# Convert the sparse matrix to a dense matrix
dense_matrix = sparse_matrix.toarray()
print(dense_matrix)

[[1 0 2]
 [0 3 4]
 [5 6 0]]


One use case for sparse matrices is in graph theory. Graphs can be represented as sparse matrices, where the rows and columns correspond to the vertices, and the non-zero entries correspond to the edges.

Another use case for sparse matrices is in image processing. Images can be represented as matrices, and in many cases, most of the entries in the matrix are zero (corresponding to black pixels). By using sparse matrix representations and algorithms, we can efficiently manipulate and analyze images, such as in image compression or denoising.