#### About

> Matrix calculations

Matrix calculus is a branch of calculus that deals with derivatives and integrals of matrices. It is used in many applications, such as machine learning, control theory, and optimization. In this example, we will use Python to perform some basic matrix calculus operations and explore its use case in machine learning.



In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [7]:
C = A + B#Add
print(C)

[[ 6  8]
 [10 12]]


In [3]:
C = A - B#sub
print(C)

[[-4 -4]
 [-4 -4]]


In [4]:
C = np.dot(A, B)#dot product
print(C)

[[19 22]
 [43 50]]


In [5]:
C = A.T#Transpose
print(C)

[[1 3]
 [2 4]]


In [6]:
C = np.linalg.inv(A) #inverse
print(C)

[[-2.   1. ]
 [ 1.5 -0.5]]
