#### About

> Matrices

Matrices are a fundamental data structure in linear algebra, and are used to represent collections of numbers arranged in a grid or table. In Python, we can represent matrices using lists of lists or NumPy arrays.



In [2]:
import numpy as np


In [5]:

# create a 3x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Matrices are often used to represent data in machine learning and data science applications.