#### About

> Orthogonal matrices

An orthogonal matrix is a square matrix where the columns (and rows) are orthonormal, meaning that each column has unit length and is orthogonal to every other column. In other words, an orthogonal matrix Q satisfies the equation Q^T Q = I, where Q^T is the transpose of Q and I is the identity matrix.



In [1]:
import numpy as np


In [2]:
# Create a random 3x3 matrix
A = np.random.rand(3, 3)

In [3]:
# Compute the QR decomposition of A
Q, R = np.linalg.qr(A)

In [4]:
# Check that Q is orthogonal
print(Q)
print(Q.T @ Q)

[[-0.73192065  0.09243908 -0.6750905 ]
 [-0.05278517 -0.99546983 -0.07907941]
 [-0.67934225 -0.02224509  0.73348433]]
[[ 1.00000000e+00 -1.10105980e-18  1.36749262e-16]
 [-1.10105980e-18  1.00000000e+00 -1.42567545e-17]
 [ 1.36749262e-16 -1.42567545e-17  1.00000000e+00]]


Printing out Q and the product Q^T Q, which should be equal to the identity matrix I which demonstrates that Q is indeed orthogonal which doesn't validate in this case.

One use case for orthogonal matrices is in linear regression, where the least squares solution can be expressed as a matrix multiplication using the QR decomposition. 