#### About

> Linear independence and basis

Linear independence and basis are important concepts in linear algebra that are used to describe the structure of vector spaces.

- Linear Independence:
A set of vectors in a vector space is said to be linearly independent if no vector in the set can be written as a linear combination of the others. In other words, the only way to obtain the zero vector as a linear combination of the vectors in the set is by setting all the coefficients to zero.

- Basis:
A basis for a vector space is a set of linearly independent vectors that span the entire space, meaning that any vector in the space can be written as a linear combination of the basis vectors.




In [1]:
import numpy as np


In [2]:
# Define three vectors in R3
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
v3 = np.array([0, 0, 1])



In [3]:
# Define another vector in R3
w = np.array([2, 3, 1])


In [4]:
# Test linear independence of v1, v2, and v3
matrix = np.stack((v1, v2, v3), axis=1)
rank = np.linalg.matrix_rank(matrix)
if rank == 3:
    print("v1, v2, and v3 are linearly independent")
else:
    print("v1, v2, and v3 are linearly dependent")

v1, v2, and v3 are linearly independent


In [5]:
# Test whether w is in the span of v1, v2, and v3
matrix = np.stack((v1, v2, v3, w), axis=1)
rank = np.linalg.matrix_rank(matrix)
if rank == 3:
    print("w can be expressed as a linear combination of v1, v2, and v3")
else:
    print("w cannot be expressed as a linear combination of v1, v2, and v3")


w can be expressed as a linear combination of v1, v2, and v3


In [6]:
# Find a basis for the span of v1, v2, and v3
matrix = np.stack((v1, v2, v3), axis=1)
basis = np.linalg.qr(matrix)[0]
print("A basis for the span of v1, v2, and v3 is:")
print(basis)

A basis for the span of v1, v2, and v3 is:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
