#### About

> Singular Value Decomposition(SVD)

Singular Value Decomposition (SVD) is a matrix factorization technique that factorizes a matrix into three matrices with specific properties. Given an m x n matrix A, SVD factorizes A into the product of three matrices: U, Σ, and V*, where U and V* are unitary matrices, and Σ is a diagonal matrix with non-negative real entries.



In [1]:
import numpy as np


In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


In [3]:
# Compute the SVD of A
U, s, Vh = np.linalg.svd(A)

In [4]:
# Construct the diagonal matrix Σ
Sigma = np.zeros_like(A)
Sigma[:min(A.shape), :min(A.shape)] = np.diag(s)

# Reconstruct the original matrix A
A_reconstructed = U @ Sigma @ Vh

print("Original matrix A:")
print(A)
print("Reconstructed matrix A:")
print(A_reconstructed)

Original matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reconstructed matrix A:
[[0.95971562 1.9003033  2.84089098]
 [3.80147605 4.74858462 5.69569319]
 [6.64323649 7.59686594 8.5504954 ]]


#### Use cases

1. Data compression - To compress a high dimensional data by representing it in a lower dimensional space while retaining as much information as possible.

2. Collaborative filtering - It can be used to build recommender systems by identifying latent features in a user-item interaction matrix.

3. PCA - It can be used to identify the most important features in a dataset and reduce its dimensionality.

4. Image processing - It can be used to perform image compression and denoising by representing images as a combination of basis images.