#### About

> Jordan Canonical Form

The Jordan canonical form is a way to decompose a matrix into simpler parts that can be easier to work with. Specifically, it transforms a matrix into a block diagonal form where each block corresponds to a Jordan block, which is a matrix that has a specific structure.

The Jordan blocks are constructed by taking the eigenvalues of the matrix and constructing a block for each eigenvalue. Each block has the eigenvalue along its diagonal, and 1's above the diagonal. If there are multiple blocks corresponding to the same eigenvalue, they are arranged in a specific way that depends on the dimension of the blocks and the number of blocks.





In [1]:
import numpy as np



In [2]:
# Define the matrix
A = np.array([[3, 1, 0], [0, 3, 1], [0, 0, 3]])


In [3]:
# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

In [5]:
# compute jordan canonical form
P = eigenvectors
D = np.zeros_like(A)
i = 0
while i < len(eigenvalues):
    eigenvalue = eigenvalues[i]
    block_size = np.count_nonzero(eigenvalues == eigenvalue)
    block = np.diag(np.ones(block_size)*eigenvalue) + np.diag(np.ones(block_size-1), k=1)
    D[i:i+block_size, i:i+block_size] = block
    i += block_size

In [6]:
J = np.linalg.inv(P) @ A @ P
print("Jordan canonical form:\n", J)

Jordan canonical form:
 [[ 3.00000000e+00  8.88178420e-16 -2.22044605e-16]
 [ 0.00000000e+00  3.00000000e+00  4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  3.00000000e+00]]
