#### About

> Support Vector Machines

Support Vector Machines (SVMs) are a type of supervised machine learning algorithm used for classification and regression tasks. SVMs are particularly known for their ability to handle complex decision boundaries and work well with high-dimensional data. The key idea behind SVMs is to find the best hyperplane that separates different classes of data points, while maximizing the margin between the classes.

> Mathematics

1. Hyperplane - In a binary classification problem, an SVM finds the optimal hyperplane that best separates the data points of two classes. A hyperplane is a flat, n-dimensional surface (where n is the number of features in the data) that divides the data points into different classes. For a two-dimensional feature space, a hyperplane is simply a line that separates the data points of two classes.

2. Margin - The margin is the distance between the hyperplane and the nearest data points of each class. SVM aims to find the hyperplane that has the maximum margin between the classes, as it is likely to generalize well to new, unseen data. The data points that lie on the margin are called support vectors, as they play a crucial role in defining the hyperplane.

3. Soft Margin - In some cases, it may not be possible to find a hyperplane that perfectly separates the data points of two classes. SVM allows for a soft margin, where some data points may be misclassified, but a trade-off is made to achieve a wider margin. This is controlled by a hyperparameter called the "C" parameter, which balances the trade-off between achieving a wider margin and allowing misclassifications.

4. Kernel Trick - SVMs can also handle non-linear decision boundaries by using a kernel function. A kernel function maps the data points into a higher-dimensional feature space, where a linear hyperplane can then separate the classes. This allows SVMs to handle complex patterns in the data without explicitly defining the higher-dimensional feature space. Examples - RBF(Radial Basis function) etc





In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [2]:
iris = load_iris()
X = iris.data
y = iris.target


In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [4]:
#scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [5]:
clf = SVC(kernel='rbf', random_state=42)
clf.fit(X_train, y_train)


SVC(random_state=42)

In [6]:
# Make predictions on test data
y_pred = clf.predict(X_test)

In [7]:
# Calculate accuracy and create a confusion matrix
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

In [8]:
print(accuracy)

1.0


In [9]:
print(confusion)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
